services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /my/own/datadir:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /my/own/redisdir:/data
